//@Author Andrew Furey
//@Date: 3–15–2021
//@Email:
//@FileName: userRequest.http

###
GET http://localhost:8080/patient/onePatient
Content-Type: application/json

{
    
    "patientBDay" : "1970-04-15"
}


###
POST http://localhost:8080/schedule/
Content-Type: application/json

{
    
    "apptTime" :"2021-05-02T10:45:00", "patientId":"1", "orderId":"1", "dateCreated":"2021-04-05T07:54", "dateEdited":"2021-04-11T11:57:00"
}
###
POST http://localhost:8080/user
Content-Type: application/json

{
    "firstName":"Bilbo", "lastName":"Bagins", "username":"bbagins.underhill", "email":"bbagins@MidEarth.com", 
    "password":"MyPrecious", "phone":"555-555-5555","address":"The Shire","title":"Radiologist", "isActive":true, 
    "hireDate":"2021-03-15","enabled": true, "locked":false, "userRole":"ROLE_MEDICAL"
}

###
POST http://localhost:8080/registration
Content-Type: application/json

{
    "firstName":"Bilbo", "lastName":"Bagins", "username":"bbagins.underhill", "email":"bbagins@MidEarth.com", 
    "password":"MyPrecious","phone":"555-555-5555", "dob":"1966-02-25", "userRole":"MEDICAL", "position":"Burglar", 
    "hireDate":"2021-03-15"
}

###
POST http://localhost:8080/patient
Content-Type: application/json

{
    "firstName":"Steve", "lastName":"Rogers", "email":"cap@avengers.gov", "phone":"123-555-4567", 
    "birthDate":"1918-07-04", "allergy_asthma":false,"allergy_ltx":false,"allergy_mriDye":false,
    "allergy_xrayDye":false, "notes":"Given a dose of an experimental super soldier serum in the 1940's"
}

###
DELETE  http://localhost:8080/user/3

###
PUT   http://localhost:8080/user/1?name=Nick&email=nfury@shield.com
Content-Type: application/json