//@Author Andrew Furey
//@Date: 3–15–2021
//@Email:
//@FileName: userRequest.http

###
POST http://localhost:8080/api/v1/User
Content-Type: application/json

{
    "firstName":"Bilbo", "lastName":"Bagins", "username":"bbagins.underhill", "email":"bbagins@MidEarth.com", 
    "password":"MyPrecious", "phone":"555-555-5555", "dob":"1966-02-25", "isActive":true, "userRole":"MEDICAL", 
    "enabled": true, "locked":false, "position":"Burglar","hireDate":"2021-03-15"
}

###
POST http://localhost:8080/api/v1/Registration
Content-Type: application/json

{
    "firstName":"Bilbo", "lastName":"Bagins", "username":"bbagins.underhill", "email":"ajfurey@gmail.com", 
    "password":"MyPrecious","phone":"555-555-5555", "dob":"1966-02-25", "userRole":"MEDICAL", "position":"Burglar", 
    "hireDate":"2021-03-15"
}
###
DELETE  http://localhost:8080/api/v1/User/3

###
PUT   http://localhost:8080/api/v1/User/1?name=Nick&email=nfury@shield.com
Content-Type: application/json